/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/H1daNkdSVWi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"

export function Hero() {
  const [isDarkMode, setIsDarkMode] = useState(false)
  return (
    <div className={`${isDarkMode ? "dark" : ""}`}>
      <header className="w-full h-16 bg-background dark:bg-background-dark flex items-center px-4 md:px-6 shadow-md">
        <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
          <MountainIcon className="w-6 h-6" />
        </Link>
      </header>
      <section className="mt-[1rem] w-full py-12 md:py-24 lg:py-32 xl:py-48 flex flex-col items-start justify-start">
        <div className="container px-4 md:px-6 space-y-4">
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold tracking-tighter">
            Build your{" "}
            <span className="bg-clip-text text-transparent bg-primary">
              library
            </span>
          </h1>
          <p className="max-w-[700px] text-muted-foreground md:text-xl dark:text-muted-foreground-dark">
            Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open
            Source.
          </p>
          <div className="flex flex-col gap-2 min-[400px]:flex-row">
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 dark:bg-primary-dark dark:text-primary-foreground-dark"
              prefetch={false}
            >
              Get Started
            </Link>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 dark:bg-background-dark dark:border-input-dark dark:hover:bg-accent-dark dark:hover:text-accent-foreground-dark"
              prefetch={false}
            >
              Learn more
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
